source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CoreTextView_Example', :exclusive => true do
  pod "CoreTextView", :path => "../"
end

target 'CoreTextView_Tests', :exclusive => true do
  pod "CoreTextView", :path => "../"

  
end
